---
# - name: Install pip
#   easy_install:
#     name: pip
#     state: latest

- name: Install pip3
  become: true
  become_user: root
  apt:
    name: python3-pip
    state: latest

### FIXME: workaround for https://github.com/ethereum/web3.py/issues/660
- name: Install pip3 packages (eth-utils 1.0.0b1)
  become: true
  become_user: root
  pip:
    name: eth-utils
    version: 1.0.0b1
    executable: pip3

- name: Install pip3 packages (web3)
  become: true
  become_user: root
  pip:
    name: web3
    version: 4.0.0b9
    executable: pip3

- name: Install pip3 packages (toml)
  become: true
  become_user: root
  pip:
    name: toml
    executable: pip3

### deploy token
- name: Create token deployment script
  template:
    src: token_foreign.py.j2
    dest: "{{ base_path }}/bridge/token/token_foreign.py"

- name: Deploy token on foreign
  command: "python3 token_foreign.py"
  args:
    chdir: "{{ base_path }}/bridge/token"

### register token
- name: Create token register script
  template:
    src: foreign_tokenreg.py.j2
    dest: "{{ base_path }}/bridge/contracts/foreign_tokenreg.py"

- name: Register token on foreign
  command: "python3 foreign_tokenreg.py"
  args:
    chdir: "{{ base_path }}/bridge/contracts"
